kind: Service
apiVersion: v1
metadata:
  name: loggerapp
  labels:
    app: logger
spec:
  selector:
    app: logger
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5557
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loggerapp
  labels:
    app: logger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logger
  template:
    metadata:
      labels:
        app: logger
      annotations:
        dapr.io/enabled: "true"
        dapr.io/config: app-config
        dapr.io/app-id: "loggerapp"
        dapr.io/app-port: "5557"
        dapr.io/log-as-json: "true"
    spec:
      containers:
        - name: node
          image: abrahamalcaina/logger-app:latest
          ports:
            - containerPort: 5557
          imagePullPolicy: Always
