apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: my-secret-store
spec:
  type: secretstores.kubernetes
  version: v1
  metadata:
    - name: my-secret-store

---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret-store
type: Opaque
stringData:
  super-secret: K8 :-D
